source 'https://rubygems.org'

gem 'activesupport'
gem 'cucumber', '~> 3.0.1'
gem 'faker'
gem 'gherkin'
gem 'nokogiri'
gem 'page-object', '2.0.0'
gem 'rake'
gem 'rautomation'
gem 'rspec-expectations'
gem 'selenium-webdriver'
gem 'syntax'
gem 'watir', '6.3.0'
gem 'yard'